### ISSUE TITLE
Listening on Linux crashes if the first thing I do is move on touchpad

### ISSUE THREAD

**Issue by butla** [boppreh/mouse#17]
I wasn't sure how to test if this package works (looks cool, though), but by while looking at the code I've noticed, that you can run the package and it'll start... well I'm not exactly sure what `__main__.py:27` does... Run events from input even though I don't have any stdin?

So anyway, I prepared a Python 3.6 virtualenv, and ran the package like this:

```
sudo /home/butla/.virtualenvs/ble/bin/python -m mouse
```

I've touched the touchpad and immediately saw this error:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/butla/.virtualenvs/ble/lib/python3.6/site-packages/mouse/__init__.py", line 69, in listen
    _os_mouse.listen(self.queue)
  File "/home/butla/.virtualenvs/ble/lib/python3.6/site-packages/mouse/_nixmouse.py", line 98, in listen
    if event is None:
UnboundLocalError: local variable 'event' referenced before assignment
```

After that, nothing was happening anymore when I interacted with the touchpad.

But I did a few more tries, and on one the first thing I did was to press the left button under the touchpad - then everything started working and I was seeing a stream of events:

```
{"event_type": "down", "button": "left", "time": 1515361548.220245, "event_class": "ButtonEvent"}
{"event_type": "up", "button": "left", "time": 1515361548.270112, "event_class": "ButtonEvent"}
{"event_type": "up", "button": "left", "time": 1515361548.270112, "event_class": "ButtonEvent"}
{"event_type": "up", "button": "left", "time": 1515361548.270112, "event_class": "ButtonEvent"}
{"event_type": "up", "button": "left", "time": 1515361548.270112, "event_class": "ButtonEvent"}
{"event_type": "up", "button": "left", "time": 1515361548.270112, "event_class": "ButtonEvent"}
{"event_type": "down", "button": "?", "time": 1515361548.886853, "event_class": "ButtonEvent"}
{"event_type": "down", "button": "?", "time": 1515361548.886853, "event_class": "ButtonEvent"}
{"event_type": "down", "button": "?", "time": 1515361548.886853, "event_class": "ButtonEvent"}
{"event_type": "down", "button": "?", "time": 1515361548.886853, "event_class": "ButtonEvent"}
{"event_type": "down", "button": "?", "time": 1515361548.886853, "event_class": "ButtonEvent"}
{"event_type": "down", "button": "?", "time": 1515361548.886853, "event_class": "ButtonEvent"}
{"event_type": "down", "button": "?", "time": 1515361548.886853, "event_class": "ButtonEvent"}
{"event_type": "down", "button": "?", "time": 1515361548.886853, "event_class": "ButtonEvent"}
```

Even moving on touchpad was OK.

After a short (print) debugging session, I've noticed that when I move the touchpad, the `type` variable is equal to 3, which means `EV_ABS`, which isn't accounted for in the if/else block at `_nixmouse.py:86`. So, is this just me, or did I found a bug?

I don't know if that's related somehow, but I have Alienware 15 R3, and I heard that some people had weird Linux touchpad driver issues on other Alienware models in the past.

Last bit of debug info - I'm using Kubuntu 17.10.

**Comment by ornariece** [comment]
Hi,
I have the exact same problem on Linux. I'm using Antergos, on a HP laptop so this is not related to your laptop model. Everything you described is the same for me, the error only occurs when i first move with the trackpad.

**Comment by ornariece** [comment]
this seems related to #10

**Comment by ornariece** [comment]
Ok it is actually fixed in the current version of the mouse module, which is not available with pip for now.
