### ISSUE TITLE
AttributeError: module 'mouse' has no attribute...

### ISSUE THREAD

**Issue by fastriffs** [boppreh/mouse#34]
Hello,

Using any mouse functions generates for example:

import mouse
def test():
    print('a')
mouse.on_click(test)

AttributeError: module 'mouse' has no attribute 'on_click'

This error shows up with any mouse function

Im using python 3.7.0 on windows 7. I see that mouse is installed under pip list.  'Import mouse' does not generate any error.

**Comment by AakankshaDC** [comment]
Not sure about Windows but it took some digging to realize that the package isnt supported in MacOS - 
```
ac@MacBook-Pro ~ % python3 -m pip install mouse
Collecting mouse
  Using cached mouse-0.7.1-py2.py3-none-any.whl (16 kB)
Installing collected packages: mouse
Successfully installed mouse-0.7.1
ac@MacBook-Pro ~ % python3
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mouse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mouse/__init__.py", line 56, in <module>
    raise OSError("Unsupported platform '{}'".format(_platform.system()))
OSError: Unsupported platform 'Darwin'
```
